/**
 * Quote data & theme definitions
 * Spider-Man inspired original lines (learning MVP — not movie dialogue quotes)
 */

const CATEGORIES = [
  "Motivation",
  "Courage",
  "Growth",
  "Responsibility",
  "Love",
  "Life",
  "Hope",
  "Success",
];

const THEMES = [
  {
    id: "minimal",
    name: "Minimal",
    type: "solid",
    background: "#E8E2D8",
    textColor: "#222222",
    gradient: "linear-gradient(160deg, #E8E2D8 0%, #d4cdc0 100%)",
  },
  {
    id: "dark",
    name: "Dark",
    type: "solid",
    background: "#111827",
    textColor: "#ffffff",
    gradient: "linear-gradient(160deg, #111827 0%, #030712 100%)",
  },
  {
    id: "nature",
    name: "Nature",
    type: "photo",
    textColor: "#ffffff",
    gradient:
      "linear-gradient(160deg, #1b4332 0%, #2d6a4f 40%, #95d5b2 100%)",
  },
  {
    id: "sunset",
    name: "Sunset",
    type: "photo",
    textColor: "#ffffff",
    gradient:
      "linear-gradient(160deg, #ff6b35 0%, #f7c59f 45%, #ef476f 100%)",
  },
  {
    id: "ocean",
    name: "Ocean",
    type: "photo",
    textColor: "#ffffff",
    gradient:
      "linear-gradient(160deg, #023e8a 0%, #0077b6 50%, #90e0ef 100%)",
  },
  {
    id: "mountain",
    name: "Mountain",
    type: "photo",
    textColor: "#ffffff",
    gradient:
      "linear-gradient(180deg, #4a5568 0%, #2d3748 40%, #e2e8f0 100%)",
  },
  {
    id: "space",
    name: "Space",
    type: "photo",
    textColor: "#ffffff",
    gradient:
      "linear-gradient(160deg, #0b1026 0%, #1a1a40 45%, #533483 100%)",
  },
  {
    id: "cinematic",
    name: "Cinematic",
    type: "photo",
    textColor: "#ffffff",
    gradient:
      "linear-gradient(135deg, #1a0000 0%, #7f1d1d 40%, #450a0a 100%)",
  },
];

/** List-card accent gradients (xref xc1504 list look) */
const LIST_GRADIENTS = [
  "linear-gradient(135deg, #0ea5e9 0%, #22c55e 100%)",
  "linear-gradient(135deg, #f97316 0%, #eab308 100%)",
  "linear-gradient(135deg, #ec4899 0%, #f97316 100%)",
  "linear-gradient(135deg, #8b5cf6 0%, #3b82f6 100%)",
  "linear-gradient(135deg, #14b8a6 0%, #6366f1 100%)",
  "linear-gradient(135deg, #ef4444 0%, #a855f7 100%)",
  "linear-gradient(135deg, #06b6d4 0%, #2563eb 100%)",
  "linear-gradient(135deg, #84cc16 0%, #0d9488 100%)",
];

const quotes = [
  {
    id: 1,
    text: "큰 힘에는 큰 책임이 따른다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Responsibility",
    theme: "cinematic",
    image: null,
    tags: ["responsibility", "power", "choice"],
    description: "능력과 의무는 함께 온다.",
    action: "오늘 내가 도울 수 있는 작은 일을 하나 정한다.",
  },
  {
    id: 2,
    text: "두려움이 있어도 한 걸음 내딛는 사람이 영웅이다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Courage",
    theme: "mountain",
    image: null,
    tags: ["courage", "fear", "hero"],
    description: "용기는 두려움의 부재가 아니다.",
    action: "오늘 미뤄둔 일에 첫 5분만 투자한다.",
  },
  {
    id: 3,
    text: "선택은 우리를 만들고, 우리는 선택으로 성장한다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Growth",
    theme: "nature",
    image: null,
    tags: ["choice", "growth", "identity"],
    description: "매일의 선택이 정체성을 쌓는다.",
    action: "내일의 나를 위한 선택을 하나 기록한다.",
  },
  {
    id: 4,
    text: "희생은 잃는 것이 아니라, 지키는 일이다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Love",
    theme: "sunset",
    image: null,
    tags: ["sacrifice", "love", "protect"],
    description: "소중한 것을 지키는 마음이 희생을 부른다.",
    action: "소중한 사람에게 짧은 응원 메시지를 보낸다.",
  },
  {
    id: 5,
    text: "넘어져도 다시 일어나는 한, 이야기는 끝나지 않는다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Hope",
    theme: "ocean",
    image: null,
    tags: ["hope", "resilience", "rise"],
    description: "실패는 마침표가 아니라 쉼표다.",
    action: "오늘 실패한 일에서 배운 점 하나를 적는다.",
  },
  {
    id: 6,
    text: "마스크를 쓴다고 강해지는 게 아니다. 마음이 먼저다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Life",
    theme: "dark",
    image: null,
    tags: ["life", "identity", "heart"],
    description: "겉모습보다 내면의 결심이 힘을 만든다.",
    action: "오늘 하루의 의도를 한 문장으로 정한다.",
  },
  {
    id: 7,
    text: "완벽한 영웅은 없다. 포기하지 않는 사람만 있다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Motivation",
    theme: "space",
    image: null,
    tags: ["motivation", "persist", "hero"],
    description: "지속이 영웅을 만든다.",
    action: "오늘 목표에 10분만 더 집중한다.",
  },
  {
    id: 8,
    text: "성공은 박수가 아니라, 누군가의 하루를 가볍게 하는 일이다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Success",
    theme: "minimal",
    image: null,
    tags: ["success", "help", "impact"],
    description: "진정한 성공은 영향력에 있다.",
    action: "주변 사람의 부담을 덜어줄 작은 도움을 한다.",
  },
  {
    id: 9,
    text: "혼자 감당할 수 없어도, 혼자 책임질 수는 있다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Responsibility",
    theme: "cinematic",
    image: null,
    tags: ["responsibility", "alone", "duty"],
    description: "책임은 나로부터 시작한다.",
    action: "미룬 약속 하나를 오늘 정리한다.",
  },
  {
    id: 10,
    text: "도시가 잠든 밤에도, 누군가는 깨어 있어야 한다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Responsibility",
    theme: "space",
    image: null,
    tags: ["duty", "night", "watch"],
    description: "돌봄은 조용한 시간에 빛난다.",
    action: "내일의 나를 위해 잠들기 전 준비 하나를 한다.",
  },
  {
    id: 11,
    text: "높은 건물보다 높은 건, 다시 일어서려는 의지다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Courage",
    theme: "mountain",
    image: null,
    tags: ["courage", "will", "height"],
    description: "의지가 풍경을 바꾼다.",
    action: "두려운 대화를 위한 초안을 적어본다.",
  },
  {
    id: 12,
    text: "거미줄처럼 얇은 연결이, 세상을 붙잡는다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Love",
    theme: "ocean",
    image: null,
    tags: ["connection", "love", "bond"],
    description: "작은 관계가 큰 세계를 지탱한다.",
    action: "오래 연락 못 한 친구에게 안부를 전한다.",
  },
  {
    id: 13,
    text: "오늘 배우지 않으면, 내일의 나는 어제에 머문다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Growth",
    theme: "nature",
    image: null,
    tags: ["growth", "learn", "tomorrow"],
    description: "학습이 성장을 연다.",
    action: "관심 주제 글을 10분만 읽는다.",
  },
  {
    id: 14,
    text: "실수는 적이 아니라, 훈련의 일부다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Growth",
    theme: "sunset",
    image: null,
    tags: ["mistake", "practice", "growth"],
    description: "실수를 배움으로 바꾼다.",
    action: "최근 실수에서 개선 포인트 하나를 고른다.",
  },
  {
    id: 15,
    text: "희망은 크게 소리치지 않는다. 조용히 손을 내민다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Hope",
    theme: "minimal",
    image: null,
    tags: ["hope", "help", "quiet"],
    description: "희망은 행동으로 전달된다.",
    action: "누군가에게 실질적인 도움을 제안한다.",
  },
  {
    id: 16,
    text: "삶이 흔들릴수록, 중심을 잡는 연습이 필요하다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Life",
    theme: "dark",
    image: null,
    tags: ["life", "balance", "center"],
    description: "균형은 연습으로 온다.",
    action: "오늘 5분 호흡으로 마음을 정리한다.",
  },
  {
    id: 17,
    text: "동기는 불꽃이고, 습관은 난로다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Motivation",
    theme: "sunset",
    image: null,
    tags: ["motivation", "habit", "fire"],
    description: "지속 가능한 동기를 만든다.",
    action: "작은 습관 하나를 달력에 체크한다.",
  },
  {
    id: 18,
    text: "목표에 도달하는 길에도, 사람을 해치지 마라.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Success",
    theme: "ocean",
    image: null,
    tags: ["success", "ethics", "people"],
    description: "과정도 성공의 일부다.",
    action: "협력하는 동료에게 감사를 전한다.",
  },
  {
    id: 19,
    text: "내가 지키는 세상이, 결국 나를 지킨다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Life",
    theme: "space",
    image: null,
    tags: ["protect", "community", "life"],
    description: "돌봄은 순환한다.",
    action: "주변 환경을 더 안전하게 만드는 일을 한다.",
  },
  {
    id: 20,
    text: "영웅은 태어나지 않는다. 매일 선택된다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Courage",
    theme: "cinematic",
    image: null,
    tags: ["hero", "daily", "choice"],
    description: "매일의 선택이 영웅을 만든다.",
    action: "오늘 ‘영웅적’인 작은 선택을 하나 한다.",
  },
  {
    id: 21,
    text: "실패를 숨기지 말고, 다음 점프의 발판으로 써라.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Motivation",
    theme: "mountain",
    image: null,
    tags: ["failure", "jump", "motivation"],
    description: "실패는 도약의 재료다.",
    action: "실패 경험을 한 문장으로 재정의한다.",
  },
  {
    id: 22,
    text: "사랑은 약점이 아니다. 싸울 이유를 준다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Love",
    theme: "sunset",
    image: null,
    tags: ["love", "strength", "reason"],
    description: "사랑은 동력이 된다.",
    action: "아끼는 사람을 위한 시간을 30분 비운다.",
  },
  {
    id: 23,
    text: "밝은 내일이 보이면, 어두운 오늘도 건널 수 있다.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Hope",
    theme: "nature",
    image: null,
    tags: ["hope", "tomorrow", "cross"],
    description: "비전은 오늘을 견디게 한다.",
    action: "원하는 내일의 모습을 세 줄로 적는다.",
  },
  {
    id: 24,
    text: "성공의 무게를 잴 때, 함께한 손을 세어라.",
    author: "Spider-Man Collection",
    source: "Spider-Man Wisdom",
    category: "Success",
    theme: "minimal",
    image: null,
    tags: ["success", "team", "gratitude"],
    description: "성공은 공동의 결과다.",
    action: "도움을 준 세 사람에게 감사를 표한다.",
  },
];

function getThemeById(id) {
  return THEMES.find((t) => t.id === id) || THEMES[0];
}

function getQuoteById(id) {
  return quotes.find((q) => q.id === id);
}

function getListGradient(index) {
  return LIST_GRADIENTS[index % LIST_GRADIENTS.length];
}

